<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>field_Kecamatan</name>
   <tag></tag>
   <elementGuidId>89e4c376-1bfe-402b-bcfe-d154f899944b</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>XCUIElementTypeOther</value>
      <webElementGuid>e8095d19-116b-44f0-b2c1-815da65f30c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Kecamatan</value>
      <webElementGuid>4542b3b1-b609-43ce-a8c9-c1e541d3b9ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Kecamatan</value>
      <webElementGuid>9edf475a-bd7b-45a6-91ae-bf970817613f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//XCUIElementTypeOther[@name=&quot;Kecamatan&quot;]</value>
      <webElementGuid>97f5eb39-b889-4029-b6b4-2208e07546ac</webElementGuid>
   </webElementProperties>
   <locator>//XCUIElementTypeOther[@name=&quot;Kecamatan&quot;][count(. | //*[@type = 'XCUIElementTypeOther' and @name = 'Kecamatan' and @label = 'Kecamatan']) = count(//*[@type = 'XCUIElementTypeOther' and @name = 'Kecamatan' and @label = 'Kecamatan'])]</locator>
   <locatorStrategy>ATTRIBUTES</locatorStrategy>
</MobileElementEntity>
