<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Investasi</name>
   <tag></tag>
   <elementGuidId>7ea546f9-6fa1-4c79-90b3-0079c411689c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//option[@value = 'Investasi' and (text() = 'Investasi' or . = 'Investasi')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>f8428177-6cf3-4bad-be39-02ece4ca5586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Investasi</value>
      <webElementGuid>85d35e8b-b72d-43b6-90d5-084db9d1a4db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Investasi</value>
      <webElementGuid>1136b01a-82bb-45d3-a0b8-34f21f08d026</webElementGuid>
   </webElementProperties>
</WebElementEntity>
